#!/bin/bash
BASE_LOCATION="/bin/iwltech"
c="y"

source /etc/os-release
if [ $( echo $ID ) != "fedora" ] ; then
	echo "This script can only run on fedora."
	exit 1
fi

if [ $(whoami) != "root" ] ; then
	echo "Attempting to run as root..."
	sudo bash "./install-now"
	exit 0
fi

clear

read -p "This script assumes you are in the same directory as it. If not, please quit now with Ctrl+C. Otherwise, press enter."

tar -xvzf ./src.tar.gz -C ./ >> "/dev/null"
read -p "Are you sure you want to install? This will remove any existing installation. You will be prompted about configs later. [y/n] (default n): " o
if [ "$o" = "y" -o "$o" = "Y" ] ; then
	CURRENT_VER=$( grep "version=" "/bin/iwltech/version.txt" | cut -d'=' -f2 )
	NEW_VER=$( grep "version=" "./version.txt" | cut -d'=' -f2 )
	if [ $( echo "$NEW_VER" | grep '-' ) ] ; then
		NEW_VER=$( echo "$NEW_VER" | cut -d'-' -f1 )
	fi
	if [ $( echo "$CURRENT_VER" | grep '-' ) ] ; then
		CURRENT_VER=$( echo "$CURRENT_VER" | cut -d'-' -f1 )
	fi
	if [ $(($CURRENT_VER)) -gt $(($NEW_VER)) ] ; then
		read -p "Are you sure you want to install? The version to be installed is outdated. [y/n] (default: n): " iq
		if [ "$iq" != "y" -a "$iq" != "Y" ] ; then
			echo "Operation cancelled by user."
			exit 1
		fi
	elif [ $(($CURRENT_VER)) -eq $((NEW_VER)) ] ; then
		read -p "Are you sure you want to install? The version to be installed is the same as yours. Only your configs will be changed. [y/n] (default: n): " iqt
		if [ "$iqt" != "y" -a "$iqt" != "Y" ] ; then
			echo "Operation cancelled by user."
			exit 1
		fi
	fi
	echo "Starting installation..."
	if [ "$(grep "version=" "/bin/iwltech/version.txt" | cut -d'=' -f1)" != "" ] ; then
		c="n"
	fi
	rm -rf "/bin/iwltech"
	rm -rf "/var/log/iwltech"
	mkdir -p "/bin/iwltech"
	cp "./bin/iwltech" "/bin" -r
	mkdir -p "/var/log/iwltech"
	if [ "$c" = "n" ] ; then
		read -p "Do you want to keep the current configuration files? [y/n] (default: y): " k
		if [ "$k" = "n" -o "$k" = "N" ] ; then
			rm -rf "/etc/iwltech"
			mkdir -p "/etc/iwltech"
			cp "./etc/iwltech" "/etc" -r
		fi
	fi
	cp "./README.md" "/bin/iwltech/README.md" -r
	cp "./version.txt" "/bin/iwltech/version.txt" -r
	cp "./uninstall" "/bin/iwltech/uninstaller" -r
	cp "./install-now" "/bin/iwltech/install" -r
	echo "Installing dependencies... This may take a while."
	sudo dnf install rpmconf flatpak remove-retired-packages -y
	echo "Dependencies installed."
	chmod +x "/bin/iwltech/uninstaller"
	chmod +x "/bin/iwltech/installer"
	chmod +x "/bin/iwltech/install"
	chmod +x "/bin/iwltech/iwltech"
	rm -rf ./bin
	rm -rf ./etc
	read -p "Do you want to run the iwltech-util config to create custom configurations? [y/n] (default n): " config
	if [ "$config" = "y" -o "$config" = "Y" ] ; then
		sudo "/bin/iwltech/iwltech" "config" "-r=all"
	fi
	read -p "Do you want to run the iwltech-utils maintenance script twice to set it up? [y/n] (default y): " main
	if [ "$main" != "n" -a "$main" != "N" ] ; then
		sudo "/bin/iwltech/iwltech" "maintenance"
		sudo "/bin/iwltech/iwltech" "maintenance"
	fi
	echo "To have the script run on command 'iwltech', edit your .bashrc (go to ~/.bashrc) to add /bin/iwltech to your PATH. Also, edit root's .bashrc (go to /root/.bashrc) to add /bin/iwltech to its PATH as well."
	echo "Install complete. Exit the shell for changes to made. After that, run the command '/bin/iwltech/iwltech' to get started, or follow the above steps to add to PATH, then run 'iwltech' to get started."
	exit 0
else
	echo "Operation cancelled by user."
	exit 1
fi
